#### 0 - TensorFlow NLP Zero to Hero

In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

print(tf.__version__)

2.8.0


In [2]:
# Tokenizer

word = ["i love my dog", "i like edm music", "you are great!"]

tokenizer = Tokenizer(num_words = 50) # Maximum number words to keep is 50 with 50 most apperance
tokenizer.fit_on_texts(word) # Fitting function at word
word_index = tokenizer.word_index
print(word_index)

{'i': 1, 'love': 2, 'my': 3, 'dog': 4, 'like': 5, 'edm': 6, 'music': 7, 'you': 8, 'are': 9, 'great': 10}


In [3]:
# Turning sentences into data

sequences = tokenizer.texts_to_sequences(word)

padded = pad_sequences(sequences)

print(sequences)

[[1, 2, 3, 4], [1, 5, 6, 7], [8, 9, 10]]


In [4]:
print(padded)

[[ 1  2  3  4]
 [ 1  5  6  7]
 [ 0  8  9 10]]


#### 1 - Regular Expressions & Word Tokenization

#### 2 - Simple Topic Identification

#### 3 - Named-Entity Recognition

#### 4 - Fake News Classifier